# Credit card fraud detection

### Data preprocessing

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('C:\\Users\\admin\\Downloads\\creditcard.csv\\creditcard.csv')

In [3]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [6]:
data.sample(15)
# Class' is the variable and it takes value 1 in case of fraud and 0 otherwise.
# Time-Number of seconds elapsed between this transaction and the first transaction in the datase

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
63754,50855.0,-0.403224,0.430730,1.132870,-0.425459,0.114109,-0.884288,1.766713,-0.759216,-0.377051,...,-0.019374,0.301178,-0.145863,0.699704,-0.084774,0.961601,-0.456786,-0.490329,129.00,0
173690,121602.0,2.052285,-0.004612,-1.050829,0.402030,-0.042716,-1.109949,0.224958,-0.354320,0.420146,...,-0.273750,-0.611166,0.336658,0.008479,-0.287017,0.198316,-0.062559,-0.058642,2.69,0
162476,115148.0,2.161855,-1.697094,-0.905467,-1.537200,-1.383647,-0.374326,-1.253533,-0.091571,-0.932074,...,-0.127346,-0.068374,0.215248,0.539529,-0.287954,-0.205021,0.003162,-0.028321,88.00,0
185618,126746.0,-0.765498,-0.067998,0.717607,-2.250103,-0.109510,0.051602,0.754177,-0.289658,-0.336237,...,0.163882,0.863625,-0.219479,0.563522,-0.072211,-0.282953,-0.143549,-0.239092,129.00,0
17890,29005.0,-0.835531,1.100657,1.825883,0.820454,-0.156033,0.331626,0.226446,-1.642892,0.274873,...,1.527437,-0.101766,-0.015321,0.370764,0.146682,-0.315973,0.024900,-0.154935,25.08,0
69379,53397.0,1.249898,-1.017647,-0.129177,-0.732781,-0.637903,0.337714,-0.721356,0.242141,-0.373282,...,0.089628,0.109747,-0.218098,-0.826054,0.591160,-0.081023,-0.009956,-0.007355,74.43,0
187706,127652.0,2.006104,-0.127595,-1.015774,0.315159,-0.122936,-0.860338,0.046205,-0.149174,0.322701,...,-0.230339,-0.572987,0.349526,0.009194,-0.365216,0.179532,-0.073171,-0.070659,0.89,0
18217,29303.0,-2.429568,2.677230,-4.636020,1.812413,-0.918078,-1.825962,-0.542189,1.852685,-0.284151,...,-0.132405,-0.549512,-0.041652,-0.453208,-0.172611,-0.355532,0.152285,-0.212161,89.99,0
250552,154967.0,1.924620,-0.161890,-0.276388,1.592308,-0.440760,-0.297931,-0.264486,0.003940,1.217738,...,-0.521489,-1.206688,0.448110,-0.105388,-0.343233,-1.101249,0.056162,-0.031264,7.90,0
222170,142856.0,-0.614687,-0.959333,-1.705866,0.989529,2.813015,-2.020815,-0.453861,-0.004435,0.540250,...,0.327779,0.746187,0.372885,-0.948714,-1.726487,0.597495,0.307188,0.436327,12.31,0
80305,58423.0,-1.534755,0.881518,1.534067,-0.491978,-0.680565,0.693964,-0.885751,1.381750,-0.182478,...,0.400161,0.924125,-0.084317,-0.247860,-0.376895,0.428096,-0.260966,-0.034343,0.10,0
36462,38548.0,-2.127781,0.223636,0.418973,-0.257120,0.159420,0.680781,-0.314507,1.086099,0.237536,...,-0.010288,-0.056958,-0.307586,-1.215224,0.241374,0.467066,0.017624,-0.135126,62.75,0
89645,62665.0,0.726799,0.157562,-0.606022,-1.068221,0.053273,0.026695,0.449427,-0.542618,-1.130938,...,-0.720689,-1.531407,0.347054,-1.039591,-1.261328,0.483453,-0.773701,-0.380575,54.99,0
63166,50591.0,0.886618,-0.887105,1.714424,0.819155,-1.444034,1.008364,-1.156405,0.507087,1.547660,...,0.040108,0.464879,-0.086648,0.350959,0.214281,0.707438,0.038675,0.026899,87.00,0
236476,148828.0,1.684363,-1.218295,-0.681653,-0.572781,-1.120391,-0.784104,-0.470452,-0.095728,1.609011,...,0.297194,0.555884,0.110796,1.208240,-0.458093,0.629392,-0.080711,-0.011266,187.50,0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [8]:
data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [9]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [10]:
data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [20]:
legit = data[data.Class == 0]
fraud = data[data.Class == 1]
# make 2 new df containg only fault or only legit

In [15]:
fraud.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
623,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
4920,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
6108,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
6329,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1

In [16]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [18]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [19]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [21]:
data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [23]:
legit_sample = legit.sample(n=492)

In [24]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [25]:
new_dataset.sample(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
118556,75125.0,-0.406436,1.011246,1.255066,0.026091,0.191087,-0.544547,0.579768,0.098615,-0.314052,...,-0.239548,-0.621314,0.028702,0.007651,-0.250354,0.103384,0.257240,0.094352,3.99,0
203991,135065.0,0.159137,0.706812,-1.028875,-0.498160,0.453354,-0.273453,0.561981,0.307845,-0.321182,...,0.405856,1.045363,-0.098079,-1.010537,-0.143997,-0.108296,-0.104691,-0.089781,58.00,0
103685,68762.0,-0.479516,0.356747,1.974170,-0.376257,-0.092452,0.618588,-0.217359,0.161026,0.555482,...,0.280530,0.827117,-0.303968,-0.839495,-0.676149,0.365361,-0.271381,-0.079046,6.95,0
174110,121773.0,2.092707,-0.416059,-1.463067,-0.786270,-0.133088,-0.975325,-0.053931,-0.126006,0.833765,...,-0.288574,-0.852861,0.308954,-0.517370,-0.420930,0.556498,-0.118200,-0.085183,4.74,0
251904,155554.0,-1.040067,3.106703,-5.409027,3.109903,-0.887237,-2.497522,-2.073347,0.639818,-3.013331,...,0.773961,0.214868,-0.184233,-0.284091,0.493467,0.732329,0.675067,0.337076,94.82,1
209761,137693.0,-0.744667,-0.276259,0.519731,0.510717,2.736193,1.289634,0.126935,0.383181,-1.630682,...,0.314342,0.723440,-0.022796,-0.706595,-0.267965,2.434193,-0.372072,-0.283869,15.09,0
209481,137576.0,2.030887,0.072324,-2.024435,1.062480,0.892267,-0.330246,0.528469,-0.212773,0.078231,...,0.034699,0.229583,-0.157797,-1.042636,0.557448,-0.449299,-0.029316,-0.079753,26.83,0
234632,148053.0,1.261324,2.726800,-5.435019,5.342759,1.447043,-1.442584,-0.898702,0.123062,-2.748496,...,0.209086,-0.425938,-0.154440,-0.018820,0.632234,0.192922,0.468181,0.280486,1.59,1
245347,152710.0,0.051075,1.310427,0.733222,2.620282,1.402358,0.528489,1.086014,-0.146423,-1.724333,...,0.229936,0.766927,-0.189624,0.766853,-0.141401,-0.077278,-0.297595,-0.221816,2.47,1
47007,43034.0,-0.485588,0.287403,1.233630,-2.150154,0.372407,0.257327,0.161851,0.134850,-1.261852,...,-0.161419,-0.510453,-0.251421,-1.338004,0.529352,-0.429691,0.218115,0.022223,15.00,0

In [26]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [27]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,92918.678862,0.159783,-0.074549,-0.027541,0.011367,0.009405,0.009549,0.037803,0.043473,0.099183,...,0.045819,-0.025238,-0.024843,-0.004088,-0.026209,0.005456,0.017990,-0.010867,-0.017010,89.745711
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [28]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [29]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
218956  141539.0  0.649911 -2.551270 -1.188172  0.701388 -1.152538 -0.052096
175590  122402.0  1.844341 -0.730371 -0.320381  0.451478 -0.596353  0.312067
255748  157379.0  0.173475  1.172132 -1.021022 -0.080129  0.403263 -1.246673
233244  147497.0  2.048253  0.199634 -1.767104  0.506533  0.242702 -1.431284
184446  126245.0 -0.543979  0.050627  0.340437 -2.338484 -1.148504 -0.248529
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
218956  0.403706 -0.155364  0.630939  ...  1.268481  0.192319 -0.921602
175590 -0.809025  0.159997  1.342059  ... -0.001395  0.039509  0.057021
255748  0.957814 -0.196319 -0.023601  ... -0.153711  0.278791  0.973298
233244  0.304574 -0.406040  0.556188  ... -0.162466  0.195371  0.732673
184446 -0.211525 -0.482509 -1.447337  ... -0.490856  0.168436  0.742509
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
218956 -0.224275 -0.298637 -0.871818  0.157486 -0.170800  0.064458  699.00
175590  0.232784  0.275350 -0.505168  0.157375 -0.009549 -0.018295   87.90
255748 -0.139622 -0.173847 -0.267899 -0.185064 -0.346705 -0.280098   42.00
233244 -0.051100 -0.165636  0.279038 -0.096365 -0.002577 -0.030219   13.62
184446  0.241499  1.103513 -1.495551 -0.462393 -0.746283  0.305023   57.00
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [30]:
print(Y)

218956    0
175590    0
255748    0
233244    0
184446    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

### Logistic Regression

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [33]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [34]:
model = LogisticRegression()

In [35]:
model.fit(X_train, Y_train)

LogisticRegression()

In [36]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [37]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.940279542566709

In [38]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [39]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9238578680203046